apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Base64-Api
  description: Base64 Api service
  tags:
    - python
    - fastapi
    - api
  links:
    - url: https://fastapi-test.dev.tap-gitops.tanzu.dk/
      title: Base Url
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=base64
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: denmark-team
  system: base64
  providesApis:
    - base64-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: base64-api
  description: Base64 Api
spec:
  type: openapi
  lifecycle: experimental
  owner: denmark-team
  definition:
    $openapi: https://base64-api.base64.gke.tanzu.dk/openapi.json
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: base64
  description: Base64 Application
spec:
  owner: denmark-team
  domain: cloud-apps
